<a href="https://colab.research.google.com/github/abheer2005/Machine-Learning-Projects/blob/main/Kfoldcrossvalidation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits=load_digits()                  #to find out which method is best by k fold cross validation

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [ ]:
lr=LogisticRegression()
lr.fit(X_train,Y_train)
lr.score(X_test,Y_test)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [ ]:
svm=SVC()
svm.fit(X_train,Y_train)
svm.score(X_test,Y_test)

0.9925925925925926

In [ ]:
rf=RandomForestClassifier()
rf.fit(X_train,Y_train)
rf.score(X_test,Y_test)

0.987037037037037

**USING K FOLD CROSS VALIDATION**

In [ ]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [ ]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [ ]:
def get_score(model, X_train,X_test,Y_train,Y_test):
  model.fit(X_train,Y_train)
  return model.score(X_test,Y_test)

In [ ]:
get_score(SVC(),X_train,X_test,Y_train,Y_test)

0.9925925925925926

In [ ]:
get_score(LogisticRegression(),X_train,X_test,Y_train,Y_test)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [ ]:
get_score(RandomForestClassifier(),X_train,X_test,Y_train,Y_test)

0.9851851851851852

In [ ]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [ ]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test = digits.data[train_index], digits.data[test_index]
    Y_train, Y_test = digits.target[train_index], digits.target[test_index]

    scores_l.append(get_score(LogisticRegression(max_iter=1000), X_train, X_test, Y_train, Y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, Y_train, Y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, Y_train, Y_test))


In [ ]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test = digits.data[train_index], digits.data[test_index]
    Y_train, Y_test = digits.target[train_index], digits.target[test_index]

    print(get_score(LogisticRegression(max_iter=1000), X_train, X_test, Y_train, Y_test))
    print(get_score(SVC(), X_train, X_test, Y_train, Y_test))
    print(get_score(RandomForestClassifier(), X_train, X_test, Y_train, Y_test))


0.9248747913188647
0.9666110183639399
0.9315525876460768
0.9432387312186978
0.9816360601001669
0.9515859766277128
0.9148580968280468
0.9549248747913188
0.9232053422370617


In [ ]:
scores_l

[0.9248747913188647, 0.9432387312186978, 0.9148580968280468]

In [ ]:
scores_rf

[0.9382303839732888, 0.9432387312186978, 0.9248747913188647]

In [ ]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [ ]:
from sklearn.model_selection import cross_val_score

In [ ]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [ ]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [ ]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)

array([0.93055556, 0.90833333, 0.95821727, 0.96657382, 0.93036212])

In [ ]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.94444444, 0.90277778, 0.95543175, 0.96100279, 0.92479109])

In [ ]:
cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target)

array([0.84444444, 0.8       , 0.88300836, 0.91086351, 0.8356546 ])

In [ ]:
cross_val_score(RandomForestClassifier(n_estimators=15),digits.data,digits.target)

array([0.91388889, 0.89722222, 0.94986072, 0.95821727, 0.90529248])

In [ ]:
cross_val_score(RandomForestClassifier(n_estimators=60),digits.data,digits.target)

array([0.94166667, 0.90555556, 0.96100279, 0.95821727, 0.91922006])